// Edit a person's entry here to update their card and profile.
// Images are optional; put new portraits in images/people/ and reference them below.
window.GLAMOUR_CONTENT = window.GLAMOUR_CONTENT || {};

window.GLAMOUR_CONTENT.people = [
  {
    name: "Amy Greenwald",
    group: "Faculty",
    role: "Professor of Computer Science",
    image: "images/people/amy-greenwald.jpg",
    color: "#d9b8a3",
    bio: "Amy Greenwald leads the E-GLAMOUR Group at Brown University. Her research studies artificial intelligence, multiagent systems, reinforcement learning, and algorithmic game theory.",
    links: [
      { label: "Google Scholar", url: "https://scholar.google.com/citations?user=aQCRuYQAAAAJ&hl=en" },
      { label: "Website", url: "https://amygreenwaldblog.wordpress.com/" },
    ],
  },
  {
    name: "Klara Chura",
    group: "PhD & Masters Students",
    role: "PhD",
    image: "images/people/klara.jpg",
    color: "#b8a89e",
    bio: "",
    links: [],
  },
  {
    name: "Emin Alp Güneri",
    group: "PhD & Masters Students",
    role: "Master's",
    image: "",
    color: "#d6c2a8",
    bio: "",
    links: [],
  },
  {
    name: "Hrithik Nambiar",
    group: "PhD & Masters Students",
    role: "PhD",
    image: "images/people/hrithik.jpg",
    color: "#d4a5a5",
    bio: "",
    links: [],
  },
  {
    name: "Arjun Prakash",
    group: "PhD & Masters Students",
    role: "PhD",
    image: "images/people/arjun.jpg",
    color: "#a8c5d1",
    bio: "",
    links: [],
  },
  {
    name: "Kevin Wang",
    group: "PhD & Masters Students",
    role: "PhD",
    image: "",
    color: "#c9a87d",
    bio: "",
    links: [],
  },
  {
    name: "Tyrone Serapio",
    group: "Undergraduates",
    role: "",
    image: "images/people/tyrone.png",
    color: "#d1b8a8",
    bio: "",
    links: [],
  },
  {
    name: "Haoyang Xu",
    group: "Undergraduates",
    role: "",
    image: "",
    color: "#a8c2d1",
    bio: "",
    links: [],
  },
  {
    name: "Luke Zhang",
    group: "Undergraduates",
    role: "",
    image: "",
    color: "#b8c4d8",
    bio: "",
    links: [],
  },
  {
    name: "Naicheng He",
    group: "Alumni",
    role: "Former Undergraduate",
    image: "",
    color: "#d1b8a8",
    bio: "",
    links: [],
  },
  {
    name: "Denizalp Goktas",
    group: "Alumni",
    role: "Former PhD Student",
    image: "images/people/denizalp-goktas.jpg",
    color: "#b7c8bd",
    bio: "",
    links: [],
  },
  {
    name: "Enrique Areyan",
    group: "Alumni",
    role: "Former PhD Student",
    image: "images/people/enrique-areyan-viqueira.jpg",
    color: "#c8b8a8",
    bio: "",
    links: [],
  },
  {
    name: "Jack Ciabaton",
    group: "Alumni",
    role: "Former Undergraduate",
    image: "images/people/jack-ciabaton.jpg",
    color: "#aec1d1",
    bio: "",
    links: [],
  },
  {
    name: "John Randolph",
    group: "Alumni",
    role: "Former Undergraduate",
    image: "images/people/john-randolph.jpg",
    color: "#d2bea8",
    bio: "",
    links: [],
  },
  {
    name: "Marilyn George",
    group: "Alumni",
    role: "Former PhD Student",
    image: "images/people/marilyn-george.jpg",
    color: "#c6b4c8",
    bio: "",
    links: [],
  },
  {
    name: "Rigel Galgana",
    group: "Alumni",
    role: "Former Undergraduate",
    image: "images/people/rigel-galgana.jpg",
    color: "#abc7c7",
    bio: "",
    links: [],
  },
  {
    name: "Takehiro Oyakawa",
    group: "Alumni",
    role: "Former PhD student",
    image: "images/people/takehiro-oyakawa.jpg",
    color: "#c7b29d",
    bio: "",
    links: [],
  },
];

window.GLAMOUR_CONTENT.peopleGroups = [
  "Faculty",
  "PhD & Masters Students",
  "Undergraduates",
  "Alumni",
];
